### ISSUE TITLE
Unable to view sub-calendars in list

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNN.Events#127]
## Describe the bug
Unable to view sub-calendars in list

## To Reproduce
1. Go to Event Module Settings
2. Click on Sub-calendar tab
3. Scroll down to Add/Remove Sub-Calendars
4. Unable to see the Available or Selected in sub-calendars menu however you can select them and they do appear when you do.

## Expected behavior
Ability to see the names of the sub calendars

## Screenshots
![dnn-events-unable-to-see-sub-calendars-highlighted](https://user-images.githubusercontent.com/13577556/44813715-546e7c00-ab8f-11e8-9a8d-fada407520ef.png)
![dnn-events-unable-to-see-sub-calendars](https://user-images.githubusercontent.com/13577556/44813728-5afcf380-ab8f-11e8-9945-f17cf187e3f2.png)

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

**Comment by EPTamminga** [comment]
Solved in the 7.0.3 version that is under development. Please note that the **module title** of the sub-calendars is used for display & selection, so you sub-calendar module must have a module title in order to be displayed.
![image](https://user-images.githubusercontent.com/5859855/45213147-05170280-b297-11e8-9ad8-201a873a083d.png)
