### ISSUE TITLE
Responsive styling

### ISSUE THREAD

**Issue by mitcheal** [DNNCommunity/DNN.Events#14]
Is the module responsive friendly?

**Comment by thabaum** [comment]
I believe making this "Touch Friendly" would be key since most devices being used are touch friendly.  The module can use a boost in this area as the little plus sign is great for not taking up space but hard to notice to post a listing for a new user.

A module that looks like Events for Dummies would be a great approach to the templates, buttons and such.  Keep the templates that are here but maybe a switch that makes it more touch friendly and uses a responsive touch version of templates would be AWESOME!

**Comment by EPTamminga** [comment]
A good comment and suggestion, buit.... can you contribute here to get it done to a certain extend?

**Comment by thabaum** [comment]
When the dust settles here I will see what I can do to make something happen.  I am getting closer to wrapping my brain around all the new changes.
