### ISSUE TITLE
Version 6.03 not listing sub calendars and recurring events

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNN.Events#19]
It seems during upgrading to 8.0 dnn install then updating to 6.3 events module I have events that should be recurring, they are still there in the past but the series has been broken.

Also I cannot add sub calendars to be viewed so that I can post the calendar on multiple pages (such as a list on the home page and the month view on the events page).  I go to add sub calendars but non are listed.

For the recurring events I tried editing the series and update to see if it would put them in the calendar for lets say Christmas... no luck.

**Comment by EPTamminga** [comment]
Tnx for the feedback. 
I did not change anything substantial in de normal coding, mainly the referencing DNN Telerik based controls changed, so this suprises me a bit. Did you used the DNN 8 beta or the recent RC?
I will try to reproduce, but I do not have a test with all the conditions you mention, so I will do my best...

**Comment by thabaum** [comment]
I am using the RC right now latest version release.  Thank you!

**Comment by CaveDeb** [comment]
I'm having a similar issue w/ upgrade from DNN 7.x to DNN 8. Upon upgrade, home page list view showed "no events to display," even though sub-calendars were added. Half-successful go-around: after creating a copy of an event in the main calendar, then deleting the original, all events displayed in the list-view. However, IOS / Safari browser still shows "no events to display." I'm not sure yet if it's browser-specific, or across mobile in general.

**Comment by EPTamminga** [comment]
In short: not OK (yet). I will try to reproduce things, but is seems a setup that has some data to reproduce. 
I am sorry to say that time at my side is limited, especially since I will be going on PTO next week for a couple of weeks. So please do not expect a solution shortly (unless somebody steps in and solves it in the mean time).

**Comment by CaveDeb** [comment]
Thanks so much for looking into this. I'm more of a high-functioning designer rather than a developer, so I don't see myself solving the problem, but there is another (possibly related) issue that I discovered this morning. I have upgraded two DNN 7.x sites to 8.0 thus far. On one I fresh installed DNN Events 6.3.0. On the other I upgraded Events to 6.3.0 from a 6.2.x version. In both some of the event recurrence settings are missing. Here's a screen shot:
![events-recurrence-settings](https://cloud.githubusercontent.com/assets/17413119/13257162/4de00520-da13-11e5-93fa-9b1ae5fc9bca.jpg)
The site where I discovered the display issue in the list view, all events that were in the list were created in the earlier version with weekly event recurrence settings. 
I wish you well on your time off and will check back in a couple of weeks or update if I can document anything else related. Do let me know if there's any testing that would be helpful in the meantime.

**Comment by djamell** [comment]
I'm seeing this same behavior after upgrading a website from DNN 7.x to 8.0.3 with Events 6.3.0.

The Master Calendar and the Homepage List (using the Master Calendar as a subcalendar) were working fine prior to the upgrade.

Does anyone have a solution or workaround?

**Comment by djamell** [comment]
After some experimentation I have found that this problem relates to Categories.

One my Homepage List that uses the Main Calendar as a subcalendar if "Filter Events by Category" is set to "All" no Events from the subcalendar are displayed.

If I individually select the Categories the selected Category Events from the subcalendar are displayed.

**Comment by djamell** [comment]
Additional Follow Up:  It might also have something to do with the number of Categories.  If I select more than 6 categories nothing displays.

**Comment by CaveDeb** [comment]
Djamell, I'm personally using the calendars on a small charity site as a test ground, with a larger site upgrade on hold until the issue is resolved. So far my workaround wouldn't be ideal for a client to manage, but since I am the admin on the charity site, it's okay. I check the site frequently, and when the list view calendar stops displaying data, I copy an event series, then delete the original. When I do, the list view goes back to displaying all events. At one point I thought I had discovered a consistent pattern, but further tests failed to support my hypothesis.

I'm wondering, how many categories do you use on the site you described above? 

My test site had only two categories, and for most events, we didn't use them. Therefore, I had the list view set to display all. After reading your assessment above, I have just added three more categories, applied two of them to all uncategorized events, and set my list view to display the four valid categories. I'll update here with how it behaves.

**Comment by thabaum** [comment]
When in List view says "no events to display"  although I have events.  Seems to get more buggy the more I try to fix the events.  I had them listed for a while but then it quit again.  Something linked to the categories filter.

Can probably reproduce if you create a calendar then a sub calendar and try to display different events and modify the events a bit or modify the categories.

Seemed like it was working fine until I modified the category colors..

**Comment by djamell** [comment]
I agree that this has to do with some relationship between subcalendars and categories.

**Comment by djamell** [comment]
OK, I think I finally have a handle on the problem.

In Settings, Under Display -> Event List Settings, If you use "Select Events by Number" AND you have generated many Events (usually by setting up Recurring Events that extend 20 or 30 years) the list will fail and displays "No events to display".

If I reduce the number of Days (Default is 365) the list will begin to display, BUT may not display all of the events within the range.  Continuing to reduce the number of days will display more events until it appears to get everything.

So, the bug appears to be in "Select Events by Number" with regard to how many events are contained within the range of Days.

**Comment by EPTamminga** [comment]
I assume there is a limit in the # of events that can be handled in one go. I have to investigate further to see if this is a limitation can be lifted.

**Comment by djamell** [comment]
This didn't present a problem in earlier versions if that helps.

Thanks very much for looking into it when you can.
