### ISSUE TITLE
New event module features

### ISSUE THREAD

**Issue by thabaum** [DNNCommunity/DNN.Events#67]
I am wondering if there can be "Featured Events" along with a submodule feature to display them.  

- Ability to set a certain number of Featured events assigned by role.

- Also the ability to allow certain number of pictures by role.

- And the ability to set number of events a user can post by role.

- Grid View to see the posts in a grid view that loads on scrolling.

- User Profile Calendar, a way for users to post to a personal calendar

**Comment by EPTamminga** [comment]
Of course, with development everything is possible, but the question is as always: how much work and how useful?

As for the base question: can you use a category named **Featured** and use a standard Events list view to display only that category?

**Comment by thabaum** [comment]
A featured switch on or off for a posted event that can only be set be a certain role(s) or user(s)
This along with other limits for uploading photos, files and so on.

Once I get a bit more handle on changes maybe in the next couple months I can see what I can contribute to the project here if anything of value I will let you decide.   I will take a look at what can be done possibly to make a bootstrap theme with glyphicons and maybe add that grid view that loads on scrolling.  A mobile first approach... unless someone beats me to it.  Now that it is C# I would think there would be more community involvement.  I was thinking of taking this module and seeing what I can do with it for kicks myself now that it is.

**Comment by EPTamminga** [comment]
@thabaum Thank you for your support. 

We are always looking for improvements. The conversion to C# was long time on my todo list and it really took one of my developers more than 5 days to complete the job. Some issues will still come forward, since the conversion of old VB.net code (more than 10 years old with signs of legacy) is not without problems done overnight. We will squash the bugs when they are mentioned here.

Replacing the calendar (and week and list) control with modern open source .js interactive components is also a long time wish. Any help is welcome.
